"""Production migration

Revision ID: d2aec1148a06
Revises: 
Create Date: 2021-09-21 14:14:57.854747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2aec1148a06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DATETIME(), nullable=False),
    sa.Column('end', sa.DATETIME(), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantelection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participantId', sa.Integer(), nullable=False),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=256), nullable=False),
    sa.Column('participantJmbg', sa.String(length=256), nullable=False),
    sa.Column('electionId', sa.Integer(), nullable=False),
    sa.Column('pollNumber', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['electionId'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('participantelection')
    op.drop_table('participants')
    op.drop_table('elections')
    # ### end Alembic commands ###
